if(NOT DEFINED INPUT_LIST_FILE OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "INPUT_LIST_FILE and OUTPUT are required")
endif()
if(NOT EXISTS "${INPUT_LIST_FILE}")
  message(FATAL_ERROR "input list does not exist: ${INPUT_LIST_FILE}")
endif()

include("${INPUT_LIST_FILE}")
if(NOT DEFINED VECTIS_BYTE_ARRAY_INPUTS OR
   VECTIS_BYTE_ARRAY_INPUTS STREQUAL "")
  message(FATAL_ERROR "byte-array generation requires at least one input")
endif()

set(resource_output "")
set(resource_line "  ")
set(resource_line_count 0)
set(resource_first_byte TRUE)
set(resource_byte_count 0)

foreach(resource_input IN LISTS VECTIS_BYTE_ARRAY_INPUTS)
  if(NOT EXISTS "${resource_input}")
    message(FATAL_ERROR "byte-array input does not exist: ${resource_input}")
  endif()
  file(READ "${resource_input}" resource_hex HEX)
  string(LENGTH "${resource_hex}" resource_hex_length)
  math(EXPR resource_input_byte_count "${resource_hex_length} / 2")
  set(resource_offset 0)
  while(resource_offset LESS resource_input_byte_count)
    math(EXPR resource_hex_offset "${resource_offset} * 2")
    string(SUBSTRING "${resource_hex}" ${resource_hex_offset} 2 resource_byte)
    if(resource_first_byte)
      set(resource_separator "")
      set(resource_first_byte FALSE)
    else()
      set(resource_separator ", ")
    endif()
    string(APPEND resource_line "${resource_separator}0x${resource_byte}")
    math(EXPR resource_line_count "${resource_line_count} + 1")
    math(EXPR resource_byte_count "${resource_byte_count} + 1")
    if(resource_line_count EQUAL 8)
      string(APPEND resource_output "${resource_line}\n")
      set(resource_line "  ")
      set(resource_line_count 0)
    endif()
    math(EXPR resource_offset "${resource_offset} + 1")
  endwhile()
endforeach()

if(resource_byte_count EQUAL 0)
  message(FATAL_ERROR "raw byte-array input must not be empty")
endif()
if(NOT resource_line_count EQUAL 0)
  string(APPEND resource_output "${resource_line}\n")
endif()

set(resource_temporary "${OUTPUT}.tmp")
file(REMOVE "${resource_temporary}")
file(WRITE "${resource_temporary}" "${resource_output}")
file(RENAME "${resource_temporary}" "${OUTPUT}" RESULT resource_rename_result)
if(NOT resource_rename_result STREQUAL "0")
  file(REMOVE "${resource_temporary}")
  message(FATAL_ERROR "failed to publish byte array: ${resource_rename_result}")
endif()
